### ISSUE TITLE
@vision with local .png returns error 400

### ISSUE THREAD

**Issue by erosDiffusion** [microsoft/vscode-copilot-vision#83]
I have configured the api key and set openai o1-preview as model
and getting

2024-11-21 14:18:05.659 [error] Error: 400 Invalid content type. image_url is only supported by certain models.
    at Function.generate (c:\Users\slaye\.vscode\extensions\ms-vscode.vscode-copilot-vision-0.1.1\out\extension.js:9100:32)
    at c.makeStatusError (c:\Users\slaye\.vscode\extensions\ms-vscode.vscode-copilot-vision-0.1.1\out\extension.js:8783:33)
    at c.makeRequest (c:\Users\slaye\.vscode\extensions\ms-vscode.vscode-copilot-vision-0.1.1\out\extension.js:8808:138)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at create (c:\Users\slaye\.vscode\extensions\ms-vscode.vscode-copilot-vision-0.1.1\out\extension.js:1722:21)
    at Bk.y (c:\Users\slaye\.vscode\extensions\ms-vscode.vscode-copilot-vision-0.1.1\out\extension.js:1894:27)
    at Wg.$invokeAgent (file:///c:/Users/slaye/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:137:45819) 

same issue if I try with other models.
also tried the pre release plugin versio and getting the same issue.

one note is my copilot user is different than the user providing the token for api consumption, if that makes any difference

![Image](https://github.com/user-attachments/assets/5e76dcd6-1ae3-40dc-a1d5-395159b48951)

v0.1.1 
Published
2024-10-19, 05:24:55
Last released
2024-11-13, 17:51:13
Last updated
2024-11-21, 14:11:29
Identifier
ms-vscode.vscode-copilot-vision

**Comment by merlycortez** [comment]
I had the same issue. It worked for me when using 
Model: gpt-4 
Model version: vision-preview

**Comment by justschen** [comment]
looks like the issue is with the model - keep in mind that only certain deployments of gpt support vision!
